// Code generated by "stringer -type=Component -trimprefix=Component"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentNumber-0]
	_ = x[ComponentString-1]
	_ = x[ComponentDate-2]
	_ = x[ComponentTime-3]
	_ = x[ComponentTZ-4]
	_ = x[ComponentAgo-5]
	_ = x[ComponentSpecial-6]
	_ = x[ComponentEarly-7]
	_ = x[ComponentLate-8]
	_ = x[ComponentEpoch-9]
	_ = x[ComponentNow-10]
	_ = x[ComponentYesterday-11]
	_ = x[ComponentToday-12]
	_ = x[ComponentTomorrow-13]
	_ = x[ComponentZulu-14]
	_ = x[ComponentDelta-15]
	_ = x[ComponentSecond-16]
	_ = x[ComponentMinute-17]
	_ = x[ComponentHour-18]
	_ = x[ComponentDay-19]
	_ = x[ComponentWeek-20]
	_ = x[ComponentMonth-21]
	_ = x[ComponentQuarter-22]
	_ = x[ComponentYear-23]
	_ = x[ComponentDecade-24]
	_ = x[ComponentCentury-25]
	_ = x[ComponentMillennium-26]
	_ = x[ComponentMillis-27]
	_ = x[ComponentMicros-28]
	_ = x[ComponentJulian-29]
	_ = x[ComponentDOW-30]
	_ = x[ComponentDOY-31]
	_ = x[ComponentTZHour-32]
	_ = x[ComponentTZMinute-33]
	_ = x[ComponentISOYear-34]
	_ = x[ComponentISODOW-35]
}

const _Component_name = "NumberStringDateTimeTZAgoSpecialEarlyLateEpochNowYesterdayTodayTomorrowZuluDeltaSecondMinuteHourDayWeekMonthQuarterYearDecadeCenturyMillenniumMillisMicrosJulianDOWDOYTZHourTZMinuteISOYearISODOW"

var _Component_index = [...]uint8{0, 6, 12, 16, 20, 22, 25, 32, 37, 41, 46, 49, 58, 63, 71, 75, 80, 86, 92, 96, 99, 103, 108, 115, 119, 125, 132, 142, 148, 154, 160, 163, 166, 172, 180, 187, 193}

func (i Component) String() string {
	if i >= Component(len(_Component_index)-1) {
		return "Component(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Component_name[_Component_index[i]:_Component_index[i+1]]
}
