// Code generated by "stringer -type=dateTokenType -trimprefix=dateTokenType"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dateTokenTypeNumber-0]
	_ = x[dateTokenTypeString-1]
	_ = x[dateTokenTypeDate-2]
	_ = x[dateTokenTypeTime-3]
	_ = x[dateTokenTypeTZ-4]
	_ = x[dateTokenTypeSpecial-5]
}

const _dateTokenType_name = "NumberStringDateTimeTZSpecial"

var _dateTokenType_index = [...]uint8{0, 6, 12, 16, 20, 22, 29}

func (i dateTokenType) String() string {
	if i < 0 || i >= dateTokenType(len(_dateTokenType_index)-1) {
		return "dateTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dateTokenType_name[_dateTokenType_index[i]:_dateTokenType_index[i+1]]
}
