// Code generated by "stringer -type=Order -trimprefix=Order"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderMDY-0]
	_ = x[OrderDMY-1]
	_ = x[OrderYMD-2]
}

const _Order_name = "MDYDMYYMD"

var _Order_index = [...]uint8{0, 3, 6, 9}

func (i Order) String() string {
	if i >= Order(len(_Order_index)-1) {
		return "Order(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Order_name[_Order_index[i]:_Order_index[i+1]]
}
