// Code generated by "stringer -type=ParseResultType -trimprefix=ParseResultType"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseResultTypeAbsoluteTime-0]
	_ = x[ParseResultTypeRelativeTime-1]
	_ = x[ParseResultTypePosInfinity-2]
	_ = x[ParseResultTypeNegInfinity-3]
}

const _ParseResultType_name = "AbsoluteTimeRelativeTimePosInfinityNegInfinity"

var _ParseResultType_index = [...]uint8{0, 12, 24, 35, 46}

func (i ParseResultType) String() string {
	if i < 0 || i >= ParseResultType(len(_ParseResultType_index)-1) {
		return "ParseResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseResultType_name[_ParseResultType_index[i]:_ParseResultType_index[i+1]]
}
