// Code generated by "stringer -type=Style -trimprefix=Style"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StyleISO-0]
	_ = x[StyleSQL-1]
	_ = x[StylePostgres-2]
	_ = x[StyleGerman-3]
}

const _Style_name = "ISOSQLPostgresGerman"

var _Style_index = [...]uint8{0, 3, 6, 14, 20}

func (i Style) String() string {
	if i >= Style(len(_Style_index)-1) {
		return "Style(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Style_name[_Style_index[i]:_Style_index[i+1]]
}
