// Code generated by "stringer -type=tokenType -trimprefix=tokenType"; DO NOT EDIT.

package pgdatetime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenTypeNumber-0]
	_ = x[tokenTypeString-1]
	_ = x[tokenTypeDate-2]
	_ = x[tokenTypeTime-3]
	_ = x[tokenTypeTZ-4]
	_ = x[tokenTypeSpecial-5]
}

const _tokenType_name = "NumberStringDateTimeTZSpecial"

var _tokenType_index = [...]uint8{0, 6, 12, 16, 20, 22, 29}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
