name: All builds
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.16.5"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - run: ./build/gofmt.sh
      - run: ./build/govet.sh
      - run: go test -v -race ./...
